$axure.loadCurrentPage({
  "url":"mobile_completed.html",
  "generationDate":new Date(1391126843583.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"795ad223d1024867805dc61302a36350",
    "type":"Axure:Page",
    "name":"Mobile Completed",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ade6493f2d9c45eca6f2f735d0ea9513",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":300,
              "height":460}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac51fcfd29664860a52c6faba9c93361",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":300,
                  "height":460}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mobile_home/u0.png"}},
{
          "id":"aafd5569fa124075921fce2e88b85efc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":297},
            "size":{
              "width":264,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1561047e767046f9ba43c672ac5892db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":16,
                  "y":297},
                "size":{
                  "width":264,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mobile_completed/u2.png"}},
{
          "id":"a710ad073a26434e89fbd8cf1a17e6fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1}}},
            "location":{
              "x":52,
              "y":18},
            "size":{
              "width":197,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d59f510dd234eee9d20c03112ae06af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF6600,
                      "opacity":1}}},
                "location":{
                  "x":52,
                  "y":18},
                "size":{
                  "width":197,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Mobile Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mobile_home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"59933a3659654f958b211241ca6ca859",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":0,
              "y":65},
            "size":{
              "width":300,
              "height":18},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cc6baf0f3d2437c8ec45fe9f966fbfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":65},
                "size":{
                  "width":300,
                  "height":18},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mobile_home/u14.png"}},
{
          "id":"db0e4cbd6db44b218064150c5a567f11",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":25,
              "y":103},
            "size":{
              "width":244,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cb4c8c7fee54b648cfc0c31f62b93a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":25,
                  "y":103},
                "size":{
                  "width":244,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e13ea77951bf4425bd49a09e4b47f4fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":25,
              "y":216},
            "size":{
              "width":206,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d901b9a9e44e40258e8cdbb9424ea47a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":25,
                  "y":216},
                "size":{
                  "width":206,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7aeafb8430324a988c76052cacf2ec51",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "horizontalAlignment":"center",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}}},
            "location":{
              "x":26,
              "y":319},
            "size":{
              "width":234,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43fb1f50188d4afd829d7da86065aa6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "horizontalAlignment":"center",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6600}}},
                "location":{
                  "x":26,
                  "y":319},
                "size":{
                  "width":234,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Mobile Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mobile_home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"images/mobile_completed/u12_mouseOver.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ade6493f2d9c45eca6f2f735d0ea9513":{
      "scriptId":"u0"},
    "ac51fcfd29664860a52c6faba9c93361":{
      "scriptId":"u1"},
    "aafd5569fa124075921fce2e88b85efc":{
      "scriptId":"u2"},
    "1561047e767046f9ba43c672ac5892db":{
      "scriptId":"u3"},
    "a710ad073a26434e89fbd8cf1a17e6fc":{
      "scriptId":"u4"},
    "6d59f510dd234eee9d20c03112ae06af":{
      "scriptId":"u5"},
    "59933a3659654f958b211241ca6ca859":{
      "scriptId":"u6"},
    "9cc6baf0f3d2437c8ec45fe9f966fbfe":{
      "scriptId":"u7"},
    "db0e4cbd6db44b218064150c5a567f11":{
      "scriptId":"u8"},
    "3cb4c8c7fee54b648cfc0c31f62b93a0":{
      "scriptId":"u9"},
    "e13ea77951bf4425bd49a09e4b47f4fd":{
      "scriptId":"u10"},
    "d901b9a9e44e40258e8cdbb9424ea47a":{
      "scriptId":"u11"},
    "7aeafb8430324a988c76052cacf2ec51":{
      "scriptId":"u12"},
    "43fb1f50188d4afd829d7da86065aa6b":{
      "scriptId":"u13"}}});