$axure.loadCurrentPage({
  "url":"mobile_checkout.html",
  "generationDate":new Date(1391126843475.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9ce367b3bb9b48b99800a768e8815c59",
    "type":"Axure:Page",
    "name":"Mobile Checkout",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0dd963d801644c60b1dc058e4d315a01",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":300,
              "height":460}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"306a5fd4aa9d4f7da066b6912e25ef05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":300,
                  "height":460}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mobile_home/u0.png"}},
{
          "id":"f454882f95b74fd0a78aca890dc2659e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1}}},
            "location":{
              "x":52,
              "y":18},
            "size":{
              "width":197,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c8b97e628eb40c8b3b836ceff802ba4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF6600,
                      "opacity":1}}},
                "location":{
                  "x":52,
                  "y":18},
                "size":{
                  "width":197,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Mobile Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mobile_home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"b499a71e3cd44bc293ae3b0e627e316a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":0,
              "y":65},
            "size":{
              "width":300,
              "height":18},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4d33b71d1e84fe6a0c2281b9ac6a5fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":65},
                "size":{
                  "width":300,
                  "height":18},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mobile_home/u14.png"}},
{
          "id":"ca2fa88142d0475faca3c5cec435da33",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":147,
              "y":229},
            "size":{
              "width":134,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bd8f17d219c4269b7e719579836cfb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":147,
                  "y":229},
                "size":{
                  "width":134,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3e0ced5ea4a4701bd4404def7cf92f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":20,
              "y":93},
            "size":{
              "width":152,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"526e6f920fb04246844ab21315687bdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":20,
                  "y":93},
                "size":{
                  "width":152,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"951365367b74431d8b636c1d213baf44",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":134,
              "y":143},
            "size":{
              "width":147,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f57e9610dc4a488dbcafa5f26b9016b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":134,
                  "y":143},
                "size":{
                  "width":147,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e2e31a88728403f83c528d477aafa1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":134,
              "y":170},
            "size":{
              "width":114,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e8f734f438d4ea18eaa8195d7cc3c97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":134,
                  "y":170},
                "size":{
                  "width":114,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f393ae295c5d463f94873a2b82bfe02c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":135},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8aab893ab8e949f8ac24dc410435ffc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":135},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_home/u33.png"}},
{
          "id":"8ebd78e2adce4637bef74b6cbd0ce8c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":20,
              "y":157},
            "size":{
              "width":24,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8bb33b46c5b4591bfb08c256baf5e36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":20,
                  "y":157},
                "size":{
                  "width":24,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42314ab7921a42c8a947f17e8b7a391c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":20,
              "y":275},
            "size":{
              "width":192,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ad2fce66f7e4455935f41b81ac6574c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":20,
                  "y":275},
                "size":{
                  "width":192,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25d7b3755b24407bb0e9ac1a565f82e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCFF},
            "location":{
              "x":48.5,
              "y":637},
            "size":{
              "width":204,
              "height":50},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a93f5d2880f4447480aa5f3b928ffc8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6600}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF},
                "location":{
                  "x":48.5,
                  "y":637},
                "size":{
                  "width":204,
                  "height":50},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Mobile Completed in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mobile_completed.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/pc_checkout/u31.png",
            "mouseOver~":"images/pc_checkout/u31_mouseOver.png"}},
{
          "id":"ecc007bed49b4c289ce49b11e82a4ee1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":325},
            "size":{
              "width":261,
              "height":284}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bf4115df9ff4d09b73b22ea9dbf18c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":325},
                "size":{
                  "width":261,
                  "height":284}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mobile_checkout/u22.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0dd963d801644c60b1dc058e4d315a01":{
      "scriptId":"u0"},
    "306a5fd4aa9d4f7da066b6912e25ef05":{
      "scriptId":"u1"},
    "f454882f95b74fd0a78aca890dc2659e":{
      "scriptId":"u2"},
    "9c8b97e628eb40c8b3b836ceff802ba4":{
      "scriptId":"u3"},
    "b499a71e3cd44bc293ae3b0e627e316a":{
      "scriptId":"u4"},
    "f4d33b71d1e84fe6a0c2281b9ac6a5fd":{
      "scriptId":"u5"},
    "ca2fa88142d0475faca3c5cec435da33":{
      "scriptId":"u6"},
    "9bd8f17d219c4269b7e719579836cfb9":{
      "scriptId":"u7"},
    "e3e0ced5ea4a4701bd4404def7cf92f5":{
      "scriptId":"u8"},
    "526e6f920fb04246844ab21315687bdf":{
      "scriptId":"u9"},
    "951365367b74431d8b636c1d213baf44":{
      "scriptId":"u10"},
    "f57e9610dc4a488dbcafa5f26b9016b4":{
      "scriptId":"u11"},
    "2e2e31a88728403f83c528d477aafa1b":{
      "scriptId":"u12"},
    "1e8f734f438d4ea18eaa8195d7cc3c97":{
      "scriptId":"u13"},
    "f393ae295c5d463f94873a2b82bfe02c":{
      "scriptId":"u14"},
    "8aab893ab8e949f8ac24dc410435ffc5":{
      "scriptId":"u15"},
    "8ebd78e2adce4637bef74b6cbd0ce8c8":{
      "scriptId":"u16"},
    "e8bb33b46c5b4591bfb08c256baf5e36":{
      "scriptId":"u17"},
    "42314ab7921a42c8a947f17e8b7a391c":{
      "scriptId":"u18"},
    "6ad2fce66f7e4455935f41b81ac6574c":{
      "scriptId":"u19"},
    "25d7b3755b24407bb0e9ac1a565f82e5":{
      "scriptId":"u20"},
    "a93f5d2880f4447480aa5f3b928ffc8c":{
      "scriptId":"u21"},
    "ecc007bed49b4c289ce49b11e82a4ee1":{
      "scriptId":"u22"},
    "9bf4115df9ff4d09b73b22ea9dbf18c9":{
      "scriptId":"u23"}}});