$axure.loadCurrentPage({
  "url":"pc_completed.html",
  "generationDate":new Date(1391126839843.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"864ab3a70da94155ab0c925509886c25",
    "type":"Axure:Page",
    "name":"PC Completed",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"91b35da50e4b473aa79ce8dcd0a2827b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"bb22cd338d9541549370483087cdec53"},
{
          "id":"9cbb0cabd8f7496c9831ab1485498f96",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":25,
              "y":165},
            "size":{
              "width":651,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62de96c29cdb4edf9383c1f1e6bb9cc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":25,
                  "y":165},
                "size":{
                  "width":651,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc69657a4c7f4f35a9476c4e2119fa9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":25,
              "y":207},
            "size":{
              "width":360,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"047a842eccdb4feb880d991d5b8ffec3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":25,
                  "y":207},
                "size":{
                  "width":360,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cbe82216f7f948108d4df7314613f284",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":281},
            "size":{
              "width":220,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d521bfb5f0964c46a46fd3ad1259c305",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":281},
                "size":{
                  "width":220,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_product_info/u17.png"}},
{
          "id":"3b0efe00d1654918aa719d5bb7e55391",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":354,
              "y":300},
            "size":{
              "width":228,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbdf52c1c7d14f2ca21fcd4b740d0464",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":354,
                  "y":300},
                "size":{
                  "width":228,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5aa7212cae39475aa123c253c9a04d0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":342},
            "size":{
              "width":273,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb3c7c510a204f5b8cc24ed027bff023",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":342},
                "size":{
                  "width":273,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"787c874fd2ff45818218e94647759054",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}}},
            "location":{
              "x":25,
              "y":232},
            "size":{
              "width":214,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8cb2d6294084b11a59032b0429eae1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6600}}},
                "location":{
                  "x":25,
                  "y":232},
                "size":{
                  "width":214,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open PC Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"pc_home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"images/pc_completed/u27_mouseOver.png"}}]}},
  "masters":{
    "bb22cd338d9541549370483087cdec53":{
      "packageId":"bb22cd338d9541549370483087cdec53",
      "type":"Axure:Master",
      "name":"PC Header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7baeecf010af4f38aa8ded0ac4e28c00",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "stateStyles":{
                "mouseOver":{
                  "borderWidth":"3"}},
              "size":{
                "width":701,
                "height":94}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f0d7b1a954d84e3fa7ab7a103d01772e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "stateStyles":{
                    "mouseOver":{
                      "borderWidth":"3"}},
                  "size":{
                    "width":701,
                    "height":94}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/pc_home/u1.png",
              "mouseOver~":"images/pc_home/u1_mouseOver.png"}},
{
            "id":"a0a5d509808f4fb6ab895f4e46a25c3b",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF6600,
                    "opacity":1}}},
              "location":{
                "x":252,
                "y":22},
              "size":{
                "width":197,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d38ca52b75234f17933a0fe3cae1fe24",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF6600,
                        "opacity":1}}},
                  "location":{
                    "x":252,
                    "y":22},
                  "size":{
                    "width":197,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open PC Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"pc_home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif"}},
{
            "id":"ea77ede591754899bba75ff93906b9fe",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":94},
              "size":{
                "width":701,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"959aa9f77cce418395aa6a57f5e0d5a2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":94},
                  "size":{
                    "width":701,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/pc_home/u5.png"}},
{
            "id":"fdf81cb1ea394a3d95044c1064f872e2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":26,
                "y":100},
              "size":{
                "width":121,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2a78ad64d2804b1baceddf25e5856887",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":26,
                    "y":100},
                  "size":{
                    "width":121,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b2a295b832e542d48dd7d025aa1c5fd1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":184,
                "y":100},
              "size":{
                "width":54,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6cc09f9466cc4d12a6a608a98baa860b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":184,
                    "y":100},
                  "size":{
                    "width":54,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"afa25896b7fb4d118196288313f7393a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF6600,
                    "opacity":1}}},
              "location":{
                "x":283,
                "y":100},
              "size":{
                "width":80,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"15e1ef311c384599a20ee9cda3780d6b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF6600,
                        "opacity":1}}},
                  "location":{
                    "x":283,
                    "y":100},
                  "size":{
                    "width":80,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open PC Browse Products in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"pc_browse_products.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif"}},
{
            "id":"d121e8d3360744c789bec8bb549b44b9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":399,
                "y":100},
              "size":{
                "width":158,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"db0ea640dd2a4050a3a31a05dddf714e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":399,
                    "y":100},
                  "size":{
                    "width":158,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e52324a1f82b49ee960986a7ba2d7a69",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":592,
                "y":100},
              "size":{
                "width":83,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"97681ef62b5a4d11befa842e4a5edaa3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":592,
                    "y":100},
                  "size":{
                    "width":83,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "91b35da50e4b473aa79ce8dcd0a2827b":{
      "scriptId":"u0",
      "7baeecf010af4f38aa8ded0ac4e28c00":{
        "scriptId":"u1"},
      "f0d7b1a954d84e3fa7ab7a103d01772e":{
        "scriptId":"u2"},
      "a0a5d509808f4fb6ab895f4e46a25c3b":{
        "scriptId":"u3"},
      "d38ca52b75234f17933a0fe3cae1fe24":{
        "scriptId":"u4"},
      "ea77ede591754899bba75ff93906b9fe":{
        "scriptId":"u5"},
      "959aa9f77cce418395aa6a57f5e0d5a2":{
        "scriptId":"u6"},
      "fdf81cb1ea394a3d95044c1064f872e2":{
        "scriptId":"u7"},
      "2a78ad64d2804b1baceddf25e5856887":{
        "scriptId":"u8"},
      "b2a295b832e542d48dd7d025aa1c5fd1":{
        "scriptId":"u9"},
      "6cc09f9466cc4d12a6a608a98baa860b":{
        "scriptId":"u10"},
      "afa25896b7fb4d118196288313f7393a":{
        "scriptId":"u11"},
      "15e1ef311c384599a20ee9cda3780d6b":{
        "scriptId":"u12"},
      "d121e8d3360744c789bec8bb549b44b9":{
        "scriptId":"u13"},
      "db0ea640dd2a4050a3a31a05dddf714e":{
        "scriptId":"u14"},
      "e52324a1f82b49ee960986a7ba2d7a69":{
        "scriptId":"u15"},
      "97681ef62b5a4d11befa842e4a5edaa3":{
        "scriptId":"u16"}},
    "9cbb0cabd8f7496c9831ab1485498f96":{
      "scriptId":"u17"},
    "62de96c29cdb4edf9383c1f1e6bb9cc8":{
      "scriptId":"u18"},
    "bc69657a4c7f4f35a9476c4e2119fa9a":{
      "scriptId":"u19"},
    "047a842eccdb4feb880d991d5b8ffec3":{
      "scriptId":"u20"},
    "cbe82216f7f948108d4df7314613f284":{
      "scriptId":"u21"},
    "d521bfb5f0964c46a46fd3ad1259c305":{
      "scriptId":"u22"},
    "3b0efe00d1654918aa719d5bb7e55391":{
      "scriptId":"u23"},
    "fbdf52c1c7d14f2ca21fcd4b740d0464":{
      "scriptId":"u24"},
    "5aa7212cae39475aa123c253c9a04d0b":{
      "scriptId":"u25"},
    "bb3c7c510a204f5b8cc24ed027bff023":{
      "scriptId":"u26"},
    "787c874fd2ff45818218e94647759054":{
      "scriptId":"u27"},
    "a8cb2d6294084b11a59032b0429eae1e":{
      "scriptId":"u28"}}});