$axure.loadCurrentPage({
  "url":"pc_browse_products.html",
  "generationDate":new Date(1391126839114.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5a250ff27d4946c390dd4284b857534b",
    "type":"Axure:Page",
    "name":"PC Browse Products",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8f47dd38302d458093fad8aa23e11c96",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"bb22cd338d9541549370483087cdec53"},
{
          "id":"e5f2ba2f80fb430a986fe50162c89434",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":504,
              "y":201},
            "size":{
              "width":117,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10fa08f34a8948eda965e73d14ec184b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":504,
                  "y":201},
                "size":{
                  "width":117,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f89cd2dd7b0a4bc08302292bc01aee09",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":504,
              "y":239},
            "size":{
              "width":186,
              "height":287}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37587c4a4fa7436aaac867eff40c4696",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":504,
                  "y":239},
                "size":{
                  "width":186,
                  "height":287}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_home/u19.png"}},
{
          "id":"4ea9295517fe4216a3fa484297902af2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":254},
            "size":{
              "width":160,
              "height":262}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03cfcfbcaef147fc8b01e8135e8c3c66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":532,
                  "y":254},
                "size":{
                  "width":160,
                  "height":262}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"552558c72d8044cb8aa67bcc35f903d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":154},
            "size":{
              "width":484,
              "height":630}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7430cf8efe414068b83127ddd7027424",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":154},
                "size":{
                  "width":484,
                  "height":630}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_browse_products/u23.png"}},
{
          "id":"e39397da1dc8407bbe1fd56f2fda6ea2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":24,
              "y":163},
            "size":{
              "width":185,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d76e6a68671c41609bc0ba596ab44552",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":24,
                  "y":163},
                "size":{
                  "width":185,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54837c1fdd4b4bbc9d1384af2b2ea0cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":56,
              "y":201},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e48281d2ca34ea1b4d53a65bcd5dea0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":56,
                  "y":201},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_home/u33.png"}},
{
          "id":"915aa75fc16749ab80270387b3c530dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":56,
              "y":316},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7312f043e8c8430ea6e9d9ce7b97ae12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":56,
                  "y":316},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_home/u33.png"}},
{
          "id":"1c84eeef113e4556af774d6923664df8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":428},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd9b943a399645e1a35de06b8081457c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":428},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_home/u33.png"}},
{
          "id":"7a5e8d2926164b95adff84e3a19e267b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":531},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b07909f0cba74879b9f5b83c228385f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":531},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_home/u33.png"}},
{
          "id":"b928b3cd33104e8c80294559c5717fee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":634},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9558310720c042de86a20f0b693b28f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":634},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_home/u33.png"}},
{
          "id":"4bec960269d94045a4320305a3e66259",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":512,
              "y":253},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4be5ecbdf4a4fcea878ca044909924f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":253},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"1ab126ed0d3349fe9d6ede66382deab3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "horizontalAlignment":"center",
            "location":{
              "x":47,
              "y":287},
            "size":{
              "width":90,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d112a65c31914235b0936f906914f8ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"center",
                "location":{
                  "x":47,
                  "y":287},
                "size":{
                  "width":90,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26472f7749cb4b0db08ff60ee5882b99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "horizontalAlignment":"center",
            "location":{
              "x":68,
              "y":402},
            "size":{
              "width":49,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c26fb5f3ea0493a8210d6ac1fb5619e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"center",
                "location":{
                  "x":68,
                  "y":402},
                "size":{
                  "width":49,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a99bfe1acce5448eadf4ad1de13c8522",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "horizontalAlignment":"center",
            "location":{
              "x":70,
              "y":514},
            "size":{
              "width":45,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e04635b05ab466db12c39fabd93f14d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"center",
                "location":{
                  "x":70,
                  "y":514},
                "size":{
                  "width":45,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c95edde6c0c047eb91cd3f790c139c9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "horizontalAlignment":"center",
            "location":{
              "x":75,
              "y":612},
            "size":{
              "width":36,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e442b243db20417ea2f789f6bcd3697b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"center",
                "location":{
                  "x":75,
                  "y":612},
                "size":{
                  "width":36,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b183032168184b2986351971c8e0b5ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "horizontalAlignment":"center",
            "location":{
              "x":78,
              "y":720},
            "size":{
              "width":31,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a500cdc944a94e02a5a1d9c544c6543c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"center",
                "location":{
                  "x":78,
                  "y":720},
                "size":{
                  "width":31,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8b5954a27ea4cbabb46b62590354859",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":151,
              "y":207},
            "size":{
              "width":147,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b76c6756c8b4233a30c11c33a229375",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":151,
                  "y":207},
                "size":{
                  "width":147,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed19b092307d4ef2b883252a9afb58c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":238},
            "size":{
              "width":242,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcc36d653fc74442a8c911b951a862be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":238},
                "size":{
                  "width":242,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4473fad631e74cbe8ab33a69b4f5f9ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":410,
              "y":222},
            "size":{
              "width":56,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9727b3a7012449bb95c8afb45cb12b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":410,
                  "y":222},
                "size":{
                  "width":56,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d44a7b542ea4a698cb755dd394535c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":151,
              "y":322},
            "size":{
              "width":79,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e527f90456014b48bf04155edb582209",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":151,
                  "y":322},
                "size":{
                  "width":79,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb8236e9262d4bdda2cc799fc5b9430c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":353},
            "size":{
              "width":242,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecd5aa4c195643109f02425d81095d21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":353},
                "size":{
                  "width":242,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ad157f94c4a4955b300265b65bba8d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":410,
              "y":337},
            "size":{
              "width":56,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1073619d290e4793b9e24014360fad8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":410,
                  "y":337},
                "size":{
                  "width":56,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f89d802faac7472897d4dc0170290934",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":151,
              "y":434},
            "size":{
              "width":80,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fdc9975b12848f195583580f885f928",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":151,
                  "y":434},
                "size":{
                  "width":80,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aac1da2d6d61432393cbc3dabcc08a7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":465},
            "size":{
              "width":242,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"934a5f05c92740a1bfd04447f44770f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":465},
                "size":{
                  "width":242,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29f5a1b4cc7643c7bb700bea3ae0317f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":410,
              "y":449},
            "size":{
              "width":56,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05ed3efeb84e463b950dda229b9514ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":410,
                  "y":449},
                "size":{
                  "width":56,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5219cd3541214016b816863e4fd0ec1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":151,
              "y":537},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74f572c35ad742d5b674666c29acd843",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":151,
                  "y":537},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7c5f9cbcf8e4d82a9daeea124be119e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":568},
            "size":{
              "width":242,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ccb7fdf31a24188beef000ee3bbf5f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":568},
                "size":{
                  "width":242,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5abff7212b0346fca368d27d66f8c731",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":410,
              "y":552},
            "size":{
              "width":56,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6f8aeae33ce49c3bf929de84d1e8390",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":410,
                  "y":552},
                "size":{
                  "width":56,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca15ddd576984573af781fc3a4e60771",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":151,
              "y":640},
            "size":{
              "width":49,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76321270d12743dc98a39ffc7d5e43cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":151,
                  "y":640},
                "size":{
                  "width":49,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69c92b5c8011416fa0d5a4f6d9c5fe81",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":671},
            "size":{
              "width":242,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"deb88511db624003a01c737c15d290bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":671},
                "size":{
                  "width":242,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc8c59e86d7741e181c56f7feb384136",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":410,
              "y":655},
            "size":{
              "width":56,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"995e4f4bb953426cafb36af6f1000f4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":410,
                  "y":655},
                "size":{
                  "width":56,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f141c31d903846f4b74b0b50eb968ab6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "opacity":"0.3",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "borderWidth":"-1",
                "linePattern":"none"}},
            "opacity":"0",
            "location":{
              "x":47,
              "y":201},
            "size":{
              "width":427,
              "height":98},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb5dcdb293bd40649f5a53d35ea75fc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"0.3",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6600},
                    "borderWidth":"-1",
                    "linePattern":"none"}},
                "opacity":"0",
                "location":{
                  "x":47,
                  "y":201},
                "size":{
                  "width":427,
                  "height":98},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open PC Product Info in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"pc_product_info.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"images/pc_browse_products/u79_mouseOver.png"}},
{
          "id":"b827efdeab0f4eb9a72500260fac4481",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":504,
              "y":154},
            "size":{
              "width":186,
              "height":37}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "bb22cd338d9541549370483087cdec53":{
      "packageId":"bb22cd338d9541549370483087cdec53",
      "type":"Axure:Master",
      "name":"PC Header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7baeecf010af4f38aa8ded0ac4e28c00",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "stateStyles":{
                "mouseOver":{
                  "borderWidth":"3"}},
              "size":{
                "width":701,
                "height":94}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f0d7b1a954d84e3fa7ab7a103d01772e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "stateStyles":{
                    "mouseOver":{
                      "borderWidth":"3"}},
                  "size":{
                    "width":701,
                    "height":94}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/pc_home/u1.png",
              "mouseOver~":"images/pc_home/u1_mouseOver.png"}},
{
            "id":"a0a5d509808f4fb6ab895f4e46a25c3b",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF6600,
                    "opacity":1}}},
              "location":{
                "x":252,
                "y":22},
              "size":{
                "width":197,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d38ca52b75234f17933a0fe3cae1fe24",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF6600,
                        "opacity":1}}},
                  "location":{
                    "x":252,
                    "y":22},
                  "size":{
                    "width":197,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open PC Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"pc_home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif"}},
{
            "id":"ea77ede591754899bba75ff93906b9fe",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":94},
              "size":{
                "width":701,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"959aa9f77cce418395aa6a57f5e0d5a2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":94},
                  "size":{
                    "width":701,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/pc_home/u5.png"}},
{
            "id":"fdf81cb1ea394a3d95044c1064f872e2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":26,
                "y":100},
              "size":{
                "width":121,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2a78ad64d2804b1baceddf25e5856887",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":26,
                    "y":100},
                  "size":{
                    "width":121,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b2a295b832e542d48dd7d025aa1c5fd1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":184,
                "y":100},
              "size":{
                "width":54,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6cc09f9466cc4d12a6a608a98baa860b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":184,
                    "y":100},
                  "size":{
                    "width":54,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"afa25896b7fb4d118196288313f7393a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF6600,
                    "opacity":1}}},
              "location":{
                "x":283,
                "y":100},
              "size":{
                "width":80,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"15e1ef311c384599a20ee9cda3780d6b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF6600,
                        "opacity":1}}},
                  "location":{
                    "x":283,
                    "y":100},
                  "size":{
                    "width":80,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open PC Browse Products in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"pc_browse_products.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif"}},
{
            "id":"d121e8d3360744c789bec8bb549b44b9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":399,
                "y":100},
              "size":{
                "width":158,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"db0ea640dd2a4050a3a31a05dddf714e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":399,
                    "y":100},
                  "size":{
                    "width":158,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e52324a1f82b49ee960986a7ba2d7a69",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":592,
                "y":100},
              "size":{
                "width":83,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"97681ef62b5a4d11befa842e4a5edaa3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":592,
                    "y":100},
                  "size":{
                    "width":83,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "8f47dd38302d458093fad8aa23e11c96":{
      "scriptId":"u0",
      "7baeecf010af4f38aa8ded0ac4e28c00":{
        "scriptId":"u1"},
      "f0d7b1a954d84e3fa7ab7a103d01772e":{
        "scriptId":"u2"},
      "a0a5d509808f4fb6ab895f4e46a25c3b":{
        "scriptId":"u3"},
      "d38ca52b75234f17933a0fe3cae1fe24":{
        "scriptId":"u4"},
      "ea77ede591754899bba75ff93906b9fe":{
        "scriptId":"u5"},
      "959aa9f77cce418395aa6a57f5e0d5a2":{
        "scriptId":"u6"},
      "fdf81cb1ea394a3d95044c1064f872e2":{
        "scriptId":"u7"},
      "2a78ad64d2804b1baceddf25e5856887":{
        "scriptId":"u8"},
      "b2a295b832e542d48dd7d025aa1c5fd1":{
        "scriptId":"u9"},
      "6cc09f9466cc4d12a6a608a98baa860b":{
        "scriptId":"u10"},
      "afa25896b7fb4d118196288313f7393a":{
        "scriptId":"u11"},
      "15e1ef311c384599a20ee9cda3780d6b":{
        "scriptId":"u12"},
      "d121e8d3360744c789bec8bb549b44b9":{
        "scriptId":"u13"},
      "db0ea640dd2a4050a3a31a05dddf714e":{
        "scriptId":"u14"},
      "e52324a1f82b49ee960986a7ba2d7a69":{
        "scriptId":"u15"},
      "97681ef62b5a4d11befa842e4a5edaa3":{
        "scriptId":"u16"}},
    "e5f2ba2f80fb430a986fe50162c89434":{
      "scriptId":"u17"},
    "10fa08f34a8948eda965e73d14ec184b":{
      "scriptId":"u18"},
    "f89cd2dd7b0a4bc08302292bc01aee09":{
      "scriptId":"u19"},
    "37587c4a4fa7436aaac867eff40c4696":{
      "scriptId":"u20"},
    "4ea9295517fe4216a3fa484297902af2":{
      "scriptId":"u21"},
    "03cfcfbcaef147fc8b01e8135e8c3c66":{
      "scriptId":"u22"},
    "552558c72d8044cb8aa67bcc35f903d9":{
      "scriptId":"u23"},
    "7430cf8efe414068b83127ddd7027424":{
      "scriptId":"u24"},
    "e39397da1dc8407bbe1fd56f2fda6ea2":{
      "scriptId":"u25"},
    "d76e6a68671c41609bc0ba596ab44552":{
      "scriptId":"u26"},
    "54837c1fdd4b4bbc9d1384af2b2ea0cc":{
      "scriptId":"u27"},
    "3e48281d2ca34ea1b4d53a65bcd5dea0":{
      "scriptId":"u28"},
    "915aa75fc16749ab80270387b3c530dc":{
      "scriptId":"u29"},
    "7312f043e8c8430ea6e9d9ce7b97ae12":{
      "scriptId":"u30"},
    "1c84eeef113e4556af774d6923664df8":{
      "scriptId":"u31"},
    "bd9b943a399645e1a35de06b8081457c":{
      "scriptId":"u32"},
    "7a5e8d2926164b95adff84e3a19e267b":{
      "scriptId":"u33"},
    "b07909f0cba74879b9f5b83c228385f0":{
      "scriptId":"u34"},
    "b928b3cd33104e8c80294559c5717fee":{
      "scriptId":"u35"},
    "9558310720c042de86a20f0b693b28f9":{
      "scriptId":"u36"},
    "4bec960269d94045a4320305a3e66259":{
      "scriptId":"u37"},
    "d4be5ecbdf4a4fcea878ca044909924f":{
      "scriptId":"u38"},
    "1ab126ed0d3349fe9d6ede66382deab3":{
      "scriptId":"u39"},
    "d112a65c31914235b0936f906914f8ac":{
      "scriptId":"u40"},
    "26472f7749cb4b0db08ff60ee5882b99":{
      "scriptId":"u41"},
    "1c26fb5f3ea0493a8210d6ac1fb5619e":{
      "scriptId":"u42"},
    "a99bfe1acce5448eadf4ad1de13c8522":{
      "scriptId":"u43"},
    "9e04635b05ab466db12c39fabd93f14d":{
      "scriptId":"u44"},
    "c95edde6c0c047eb91cd3f790c139c9f":{
      "scriptId":"u45"},
    "e442b243db20417ea2f789f6bcd3697b":{
      "scriptId":"u46"},
    "b183032168184b2986351971c8e0b5ec":{
      "scriptId":"u47"},
    "a500cdc944a94e02a5a1d9c544c6543c":{
      "scriptId":"u48"},
    "e8b5954a27ea4cbabb46b62590354859":{
      "scriptId":"u49"},
    "8b76c6756c8b4233a30c11c33a229375":{
      "scriptId":"u50"},
    "ed19b092307d4ef2b883252a9afb58c7":{
      "scriptId":"u51"},
    "fcc36d653fc74442a8c911b951a862be":{
      "scriptId":"u52"},
    "4473fad631e74cbe8ab33a69b4f5f9ee":{
      "scriptId":"u53"},
    "b9727b3a7012449bb95c8afb45cb12b8":{
      "scriptId":"u54"},
    "4d44a7b542ea4a698cb755dd394535c7":{
      "scriptId":"u55"},
    "e527f90456014b48bf04155edb582209":{
      "scriptId":"u56"},
    "bb8236e9262d4bdda2cc799fc5b9430c":{
      "scriptId":"u57"},
    "ecd5aa4c195643109f02425d81095d21":{
      "scriptId":"u58"},
    "3ad157f94c4a4955b300265b65bba8d9":{
      "scriptId":"u59"},
    "1073619d290e4793b9e24014360fad8d":{
      "scriptId":"u60"},
    "f89d802faac7472897d4dc0170290934":{
      "scriptId":"u61"},
    "5fdc9975b12848f195583580f885f928":{
      "scriptId":"u62"},
    "aac1da2d6d61432393cbc3dabcc08a7f":{
      "scriptId":"u63"},
    "934a5f05c92740a1bfd04447f44770f9":{
      "scriptId":"u64"},
    "29f5a1b4cc7643c7bb700bea3ae0317f":{
      "scriptId":"u65"},
    "05ed3efeb84e463b950dda229b9514ad":{
      "scriptId":"u66"},
    "5219cd3541214016b816863e4fd0ec1b":{
      "scriptId":"u67"},
    "74f572c35ad742d5b674666c29acd843":{
      "scriptId":"u68"},
    "e7c5f9cbcf8e4d82a9daeea124be119e":{
      "scriptId":"u69"},
    "5ccb7fdf31a24188beef000ee3bbf5f9":{
      "scriptId":"u70"},
    "5abff7212b0346fca368d27d66f8c731":{
      "scriptId":"u71"},
    "c6f8aeae33ce49c3bf929de84d1e8390":{
      "scriptId":"u72"},
    "ca15ddd576984573af781fc3a4e60771":{
      "scriptId":"u73"},
    "76321270d12743dc98a39ffc7d5e43cb":{
      "scriptId":"u74"},
    "69c92b5c8011416fa0d5a4f6d9c5fe81":{
      "scriptId":"u75"},
    "deb88511db624003a01c737c15d290bd":{
      "scriptId":"u76"},
    "bc8c59e86d7741e181c56f7feb384136":{
      "scriptId":"u77"},
    "995e4f4bb953426cafb36af6f1000f4a":{
      "scriptId":"u78"},
    "f141c31d903846f4b74b0b50eb968ab6":{
      "scriptId":"u79"},
    "fb5dcdb293bd40649f5a53d35ea75fc8":{
      "scriptId":"u80"},
    "b827efdeab0f4eb9a72500260fac4481":{
      "scriptId":"u81"}}});