$axure.loadCurrentPage({
  "url":"mobile_product_info.html",
  "generationDate":new Date(1391126843330.17),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4598598078f34d12812505df06ad0066",
    "type":"Axure:Page",
    "name":"Mobile Product Info",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a7844be54b974c2bbe82e23fa73d1020",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":300,
              "height":460}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac6b780babe34932aab280b36e377e2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":300,
                  "height":460}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mobile_home/u0.png"}},
{
          "id":"29ca82a4fb584139a493ec9696e67201",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1}}},
            "location":{
              "x":52,
              "y":18},
            "size":{
              "width":197,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fab88dd00ae48a192b93caa6fba431a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF6600,
                      "opacity":1}}},
                "location":{
                  "x":52,
                  "y":18},
                "size":{
                  "width":197,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Mobile Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mobile_home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"a44287942443418eb185f42365a98a52",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":0,
              "y":65},
            "size":{
              "width":300,
              "height":18},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc7d6bbbb397463e937fd501768e3148",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":65},
                "size":{
                  "width":300,
                  "height":18},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mobile_home/u14.png"}},
{
          "id":"690582c96dc24f78b187a0910107d045",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":128},
            "size":{
              "width":190,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d8045dfd4884a828e0699ea12b94f19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":128},
                "size":{
                  "width":190,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mobile_product_info/u6.png"}},
{
          "id":"dd72a163347f4941827e3d8e9b2584d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":21,
              "y":91.5},
            "size":{
              "width":163,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"531cf6e6e1db4ed0a6f8e16373590cd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":21,
                  "y":91.5},
                "size":{
                  "width":163,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e58ef9ac145b4a19bce0ba45c2be28dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":220,
              "y":93},
            "size":{
              "width":114,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5190b5f1bc8b47c0bded405f961c76fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":220,
                  "y":93},
                "size":{
                  "width":114,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"500af6344364434890481e13b5910d6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":383},
            "size":{
              "width":264,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a5e0323c6ca4074a1685737220248fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":21,
                  "y":383},
                "size":{
                  "width":264,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7705334c274f417591661404fcd6aae9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":128},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c9feab1c3bf4a7dadff2b503ce78cdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":21,
                  "y":128},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_product_info/u25.png"}},
{
          "id":"74095c0c3f294b5e87beea6d283eda3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":178},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33a6efa853104aefb87b4f0a08a49459",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":21,
                  "y":178},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_product_info/u25.png"}},
{
          "id":"a8a2c15a161e4ea6a94619f4e9d6e484",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":228},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbb8ddcc8f404e67848838e54ad3406a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":21,
                  "y":228},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_product_info/u25.png"}},
{
          "id":"f5ce254335b84f819997043c4f805e84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":278},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b78caa35d9f24db7af85901692f476d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":21,
                  "y":278},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_product_info/u25.png"}},
{
          "id":"8a9d70ee092f44b69d2c5b9c62d08895",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "stateStyles":{
              "mouseOver":{
                "opacity":"0.8",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}}},
            "location":{
              "x":21,
              "y":328},
            "size":{
              "width":128,
              "height":38},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"502f686a4dca4331b268ac57285e0c55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"0.8",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6600}}},
                "location":{
                  "x":21,
                  "y":328},
                "size":{
                  "width":128,
                  "height":38},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Mobile Checkout in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mobile_checkout.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/mobile_product_info/u22.png",
            "mouseOver~":"images/mobile_product_info/u22_mouseOver.png"}},
{
          "id":"9859962134e14ffdb4fa5dde146bb219",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":157,
              "y":328},
            "size":{
              "width":128,
              "height":38},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af8353474d6d4b45b1d64788f9fa552c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":157,
                  "y":328},
                "size":{
                  "width":128,
                  "height":38},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mobile_product_info/u22.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a7844be54b974c2bbe82e23fa73d1020":{
      "scriptId":"u0"},
    "ac6b780babe34932aab280b36e377e2f":{
      "scriptId":"u1"},
    "29ca82a4fb584139a493ec9696e67201":{
      "scriptId":"u2"},
    "3fab88dd00ae48a192b93caa6fba431a":{
      "scriptId":"u3"},
    "a44287942443418eb185f42365a98a52":{
      "scriptId":"u4"},
    "cc7d6bbbb397463e937fd501768e3148":{
      "scriptId":"u5"},
    "690582c96dc24f78b187a0910107d045":{
      "scriptId":"u6"},
    "5d8045dfd4884a828e0699ea12b94f19":{
      "scriptId":"u7"},
    "dd72a163347f4941827e3d8e9b2584d7":{
      "scriptId":"u8"},
    "531cf6e6e1db4ed0a6f8e16373590cd3":{
      "scriptId":"u9"},
    "e58ef9ac145b4a19bce0ba45c2be28dd":{
      "scriptId":"u10"},
    "5190b5f1bc8b47c0bded405f961c76fd":{
      "scriptId":"u11"},
    "500af6344364434890481e13b5910d6f":{
      "scriptId":"u12"},
    "1a5e0323c6ca4074a1685737220248fe":{
      "scriptId":"u13"},
    "7705334c274f417591661404fcd6aae9":{
      "scriptId":"u14"},
    "8c9feab1c3bf4a7dadff2b503ce78cdc":{
      "scriptId":"u15"},
    "74095c0c3f294b5e87beea6d283eda3b":{
      "scriptId":"u16"},
    "33a6efa853104aefb87b4f0a08a49459":{
      "scriptId":"u17"},
    "a8a2c15a161e4ea6a94619f4e9d6e484":{
      "scriptId":"u18"},
    "fbb8ddcc8f404e67848838e54ad3406a":{
      "scriptId":"u19"},
    "f5ce254335b84f819997043c4f805e84":{
      "scriptId":"u20"},
    "b78caa35d9f24db7af85901692f476d6":{
      "scriptId":"u21"},
    "8a9d70ee092f44b69d2c5b9c62d08895":{
      "scriptId":"u22"},
    "502f686a4dca4331b268ac57285e0c55":{
      "scriptId":"u23"},
    "9859962134e14ffdb4fa5dde146bb219":{
      "scriptId":"u24"},
    "af8353474d6d4b45b1d64788f9fa552c":{
      "scriptId":"u25"}}});