$axure.loadCurrentPage({
  "url":"pc_product_info.html",
  "generationDate":new Date(1391126839451.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7c04603c5ae94400a5897ed5891fba21",
    "type":"Axure:Page",
    "name":"PC Product Info",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"47532441746547bca2cdb1222e8b00d0",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"bb22cd338d9541549370483087cdec53"},
{
          "id":"f4887962287a407dadb7374e22691ba9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":156},
            "size":{
              "width":220,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72a1d85bc0fa46b8b5c0a25fbb55dd6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":156},
                "size":{
                  "width":220,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_product_info/u17.png"}},
{
          "id":"cf774c334090461cb533d6c7325fe014",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":285,
              "y":156},
            "size":{
              "width":228,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9d5fb14a4884dd39ffc194c575ce1bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":285,
                  "y":156},
                "size":{
                  "width":228,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3cf29b035c854bfeacc81b4f4e0310dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":575,
              "y":156},
            "size":{
              "width":114,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4da07831aa4a451ca7f2a24a52a4f5dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":575,
                  "y":156},
                "size":{
                  "width":114,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"355f7ad7ec02467c94be88d0fadcd8a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":220},
            "size":{
              "width":404,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aadf58f5d6b84277ac58a91a4ae77cee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":285,
                  "y":220},
                "size":{
                  "width":404,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0bd79cd5024549b2b18ec177456399be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":386},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14edd4433f8847dfbe6d283efb809ee4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":49,
                  "y":386},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_product_info/u25.png"}},
{
          "id":"ad89f2b7b8484f3ea37846f1d4b7c729",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":386},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7211c23e9b54453d9a43008bf9356547",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":386},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_product_info/u25.png"}},
{
          "id":"cb15ed0b6dfe41a995b67c3f9772416f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":149,
              "y":386},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"465f3f86ef5440f098a338d57a1ff35d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":149,
                  "y":386},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_product_info/u25.png"}},
{
          "id":"8660c53ff0074abda98c215fc87fb6d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":199,
              "y":386},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcd9e0a88fec47029cc27fcbd722133b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":199,
                  "y":386},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_product_info/u25.png"}},
{
          "id":"2fc2878f49ce4b1997ea9dcca915ccd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":425,
              "y":476},
            "size":{
              "width":264,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d570ac927c884711bd803727071434db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":425,
                  "y":476},
                "size":{
                  "width":264,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b7aa06a163c4ab2913e631a1572ecce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":509},
            "size":{
              "width":264,
              "height":484}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e25d091a9e434b67b1bc02d23f2dca04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":425,
                  "y":509},
                "size":{
                  "width":264,
                  "height":484}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_product_info/u35.png"}},
{
          "id":"b2f1c373fc284d7ab7e98b9de75eeac0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":34,
              "y":476},
            "size":{
              "width":154,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"084435cbafdf413981717a3e13f53839",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":34,
                  "y":476},
                "size":{
                  "width":154,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5cb172a571fd4eb9a835b5332e5a7c44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "stateStyles":{
              "mouseOver":{
                "opacity":"0.8",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}}},
            "location":{
              "x":310,
              "y":370},
            "size":{
              "width":157,
              "height":47},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"643364670a1c4472a24b01cbe3f4c361",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"0.8",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6600}}},
                "location":{
                  "x":310,
                  "y":370},
                "size":{
                  "width":157,
                  "height":47},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open PC Checkout in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"pc_checkout.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/pc_product_info/u39.png",
            "mouseOver~":"images/pc_product_info/u39_mouseOver.png"}},
{
          "id":"f6862eac46274398a539d0ffe986fd59",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":496,
              "y":370},
            "size":{
              "width":157,
              "height":47},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d28cab457224fb59076cfa6975af53e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":496,
                  "y":370},
                "size":{
                  "width":157,
                  "height":47},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_product_info/u39.png"}},
{
          "id":"f88a40c0678b4c9885053e0f77a16d3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":517},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dec6f99ff0943e9baba2b1353f68e56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":35,
                  "y":517},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_home/u33.png"}},
{
          "id":"94eabd783680493389a0fad54fa6a0fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":629},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"308054eb3c5e4f4f9abd968a3f76ff3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":629},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_home/u33.png"}},
{
          "id":"eb107fb39d7b495b988fe6a2722ff82e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":732},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a5f69d0cbef472aa2b5e8056fe0bd75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":732},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_home/u33.png"}},
{
          "id":"d909f3577a6049288d0fa162f90af04e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":835},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc21c05cc2ba41058ef4c5c69ed39711",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":835},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc_home/u33.png"}},
{
          "id":"b6104feaf8e54270b938976de50900d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "horizontalAlignment":"center",
            "location":{
              "x":47,
              "y":603},
            "size":{
              "width":49,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac22dca0cbbf4ec5b5879dd30694d4d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"center",
                "location":{
                  "x":47,
                  "y":603},
                "size":{
                  "width":49,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f6e025312bf4fb082770766c1320f70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "horizontalAlignment":"center",
            "location":{
              "x":49,
              "y":715},
            "size":{
              "width":45,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f984e2c0a1f4ea99498b2d72e6ae973",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"center",
                "location":{
                  "x":49,
                  "y":715},
                "size":{
                  "width":45,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c96a04429b394b64a6d9cf9a52b32a9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "horizontalAlignment":"center",
            "location":{
              "x":54,
              "y":813},
            "size":{
              "width":36,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70f96b8f94fe4e61897190044e65024d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"center",
                "location":{
                  "x":54,
                  "y":813},
                "size":{
                  "width":36,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a6374e0245045608cbdd0aff8079176",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "horizontalAlignment":"center",
            "location":{
              "x":57,
              "y":921},
            "size":{
              "width":31,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a018c44ec96c469383b055248c981294",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"center",
                "location":{
                  "x":57,
                  "y":921},
                "size":{
                  "width":31,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"398698bff65e4d478204f2697daa7f8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":130,
              "y":523},
            "size":{
              "width":79,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfdeb54d5e284622895090f09c2db2d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":130,
                  "y":523},
                "size":{
                  "width":79,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f80b9bdec39743bc8a42d45b3d71ab28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":554},
            "size":{
              "width":242,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f50fb99ec0be4a04842eec6836525daf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":554},
                "size":{
                  "width":242,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf4816abed884ef4a05c063f4db61755",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":130,
              "y":635},
            "size":{
              "width":80,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a41cfb135e4a41a8bc3bec4a1900a285",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":130,
                  "y":635},
                "size":{
                  "width":80,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4395a3ab368947c0b8caf57028b5e8f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":666},
            "size":{
              "width":242,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40c95dd8b0864df79c98adf305cbf389",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":666},
                "size":{
                  "width":242,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a5f86271a514d2bad6b207c7b0e4458",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":130,
              "y":738},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beac4d631bc54b2c8bf1e6924bc752f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":130,
                  "y":738},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6362d91433864f2e9c93b10dba0a418a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":769},
            "size":{
              "width":242,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e4a934be952454f8156596995ea5ea3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":769},
                "size":{
                  "width":242,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5d7ef931e0e4a658d531f975aa126be",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "fontStyle":"italic",
            "location":{
              "x":130,
              "y":841},
            "size":{
              "width":49,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"324bb6486a6c42a29b3a089d30621aea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "fontStyle":"italic",
                "location":{
                  "x":130,
                  "y":841},
                "size":{
                  "width":49,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20de0fcd7a114d8dad3aa3207d2a867c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":872},
            "size":{
              "width":242,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e32e4416328d4763ac353b1ec1114841",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":872},
                "size":{
                  "width":242,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "bb22cd338d9541549370483087cdec53":{
      "packageId":"bb22cd338d9541549370483087cdec53",
      "type":"Axure:Master",
      "name":"PC Header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7baeecf010af4f38aa8ded0ac4e28c00",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "stateStyles":{
                "mouseOver":{
                  "borderWidth":"3"}},
              "size":{
                "width":701,
                "height":94}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f0d7b1a954d84e3fa7ab7a103d01772e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "stateStyles":{
                    "mouseOver":{
                      "borderWidth":"3"}},
                  "size":{
                    "width":701,
                    "height":94}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/pc_home/u1.png",
              "mouseOver~":"images/pc_home/u1_mouseOver.png"}},
{
            "id":"a0a5d509808f4fb6ab895f4e46a25c3b",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF6600,
                    "opacity":1}}},
              "location":{
                "x":252,
                "y":22},
              "size":{
                "width":197,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d38ca52b75234f17933a0fe3cae1fe24",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF6600,
                        "opacity":1}}},
                  "location":{
                    "x":252,
                    "y":22},
                  "size":{
                    "width":197,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open PC Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"pc_home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif"}},
{
            "id":"ea77ede591754899bba75ff93906b9fe",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":94},
              "size":{
                "width":701,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"959aa9f77cce418395aa6a57f5e0d5a2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":94},
                  "size":{
                    "width":701,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/pc_home/u5.png"}},
{
            "id":"fdf81cb1ea394a3d95044c1064f872e2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":26,
                "y":100},
              "size":{
                "width":121,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2a78ad64d2804b1baceddf25e5856887",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":26,
                    "y":100},
                  "size":{
                    "width":121,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b2a295b832e542d48dd7d025aa1c5fd1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":184,
                "y":100},
              "size":{
                "width":54,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6cc09f9466cc4d12a6a608a98baa860b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":184,
                    "y":100},
                  "size":{
                    "width":54,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"afa25896b7fb4d118196288313f7393a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF6600,
                    "opacity":1}}},
              "location":{
                "x":283,
                "y":100},
              "size":{
                "width":80,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"15e1ef311c384599a20ee9cda3780d6b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF6600,
                        "opacity":1}}},
                  "location":{
                    "x":283,
                    "y":100},
                  "size":{
                    "width":80,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open PC Browse Products in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"pc_browse_products.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif"}},
{
            "id":"d121e8d3360744c789bec8bb549b44b9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":399,
                "y":100},
              "size":{
                "width":158,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"db0ea640dd2a4050a3a31a05dddf714e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":399,
                    "y":100},
                  "size":{
                    "width":158,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e52324a1f82b49ee960986a7ba2d7a69",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":592,
                "y":100},
              "size":{
                "width":83,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"97681ef62b5a4d11befa842e4a5edaa3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":592,
                    "y":100},
                  "size":{
                    "width":83,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "47532441746547bca2cdb1222e8b00d0":{
      "scriptId":"u0",
      "7baeecf010af4f38aa8ded0ac4e28c00":{
        "scriptId":"u1"},
      "f0d7b1a954d84e3fa7ab7a103d01772e":{
        "scriptId":"u2"},
      "a0a5d509808f4fb6ab895f4e46a25c3b":{
        "scriptId":"u3"},
      "d38ca52b75234f17933a0fe3cae1fe24":{
        "scriptId":"u4"},
      "ea77ede591754899bba75ff93906b9fe":{
        "scriptId":"u5"},
      "959aa9f77cce418395aa6a57f5e0d5a2":{
        "scriptId":"u6"},
      "fdf81cb1ea394a3d95044c1064f872e2":{
        "scriptId":"u7"},
      "2a78ad64d2804b1baceddf25e5856887":{
        "scriptId":"u8"},
      "b2a295b832e542d48dd7d025aa1c5fd1":{
        "scriptId":"u9"},
      "6cc09f9466cc4d12a6a608a98baa860b":{
        "scriptId":"u10"},
      "afa25896b7fb4d118196288313f7393a":{
        "scriptId":"u11"},
      "15e1ef311c384599a20ee9cda3780d6b":{
        "scriptId":"u12"},
      "d121e8d3360744c789bec8bb549b44b9":{
        "scriptId":"u13"},
      "db0ea640dd2a4050a3a31a05dddf714e":{
        "scriptId":"u14"},
      "e52324a1f82b49ee960986a7ba2d7a69":{
        "scriptId":"u15"},
      "97681ef62b5a4d11befa842e4a5edaa3":{
        "scriptId":"u16"}},
    "f4887962287a407dadb7374e22691ba9":{
      "scriptId":"u17"},
    "72a1d85bc0fa46b8b5c0a25fbb55dd6f":{
      "scriptId":"u18"},
    "cf774c334090461cb533d6c7325fe014":{
      "scriptId":"u19"},
    "c9d5fb14a4884dd39ffc194c575ce1bf":{
      "scriptId":"u20"},
    "3cf29b035c854bfeacc81b4f4e0310dc":{
      "scriptId":"u21"},
    "4da07831aa4a451ca7f2a24a52a4f5dc":{
      "scriptId":"u22"},
    "355f7ad7ec02467c94be88d0fadcd8a4":{
      "scriptId":"u23"},
    "aadf58f5d6b84277ac58a91a4ae77cee":{
      "scriptId":"u24"},
    "0bd79cd5024549b2b18ec177456399be":{
      "scriptId":"u25"},
    "14edd4433f8847dfbe6d283efb809ee4":{
      "scriptId":"u26"},
    "ad89f2b7b8484f3ea37846f1d4b7c729":{
      "scriptId":"u27"},
    "7211c23e9b54453d9a43008bf9356547":{
      "scriptId":"u28"},
    "cb15ed0b6dfe41a995b67c3f9772416f":{
      "scriptId":"u29"},
    "465f3f86ef5440f098a338d57a1ff35d":{
      "scriptId":"u30"},
    "8660c53ff0074abda98c215fc87fb6d6":{
      "scriptId":"u31"},
    "dcd9e0a88fec47029cc27fcbd722133b":{
      "scriptId":"u32"},
    "2fc2878f49ce4b1997ea9dcca915ccd4":{
      "scriptId":"u33"},
    "d570ac927c884711bd803727071434db":{
      "scriptId":"u34"},
    "1b7aa06a163c4ab2913e631a1572ecce":{
      "scriptId":"u35"},
    "e25d091a9e434b67b1bc02d23f2dca04":{
      "scriptId":"u36"},
    "b2f1c373fc284d7ab7e98b9de75eeac0":{
      "scriptId":"u37"},
    "084435cbafdf413981717a3e13f53839":{
      "scriptId":"u38"},
    "5cb172a571fd4eb9a835b5332e5a7c44":{
      "scriptId":"u39"},
    "643364670a1c4472a24b01cbe3f4c361":{
      "scriptId":"u40"},
    "f6862eac46274398a539d0ffe986fd59":{
      "scriptId":"u41"},
    "5d28cab457224fb59076cfa6975af53e":{
      "scriptId":"u42"},
    "f88a40c0678b4c9885053e0f77a16d3f":{
      "scriptId":"u43"},
    "3dec6f99ff0943e9baba2b1353f68e56":{
      "scriptId":"u44"},
    "94eabd783680493389a0fad54fa6a0fd":{
      "scriptId":"u45"},
    "308054eb3c5e4f4f9abd968a3f76ff3e":{
      "scriptId":"u46"},
    "eb107fb39d7b495b988fe6a2722ff82e":{
      "scriptId":"u47"},
    "4a5f69d0cbef472aa2b5e8056fe0bd75":{
      "scriptId":"u48"},
    "d909f3577a6049288d0fa162f90af04e":{
      "scriptId":"u49"},
    "dc21c05cc2ba41058ef4c5c69ed39711":{
      "scriptId":"u50"},
    "b6104feaf8e54270b938976de50900d2":{
      "scriptId":"u51"},
    "ac22dca0cbbf4ec5b5879dd30694d4d4":{
      "scriptId":"u52"},
    "6f6e025312bf4fb082770766c1320f70":{
      "scriptId":"u53"},
    "3f984e2c0a1f4ea99498b2d72e6ae973":{
      "scriptId":"u54"},
    "c96a04429b394b64a6d9cf9a52b32a9f":{
      "scriptId":"u55"},
    "70f96b8f94fe4e61897190044e65024d":{
      "scriptId":"u56"},
    "6a6374e0245045608cbdd0aff8079176":{
      "scriptId":"u57"},
    "a018c44ec96c469383b055248c981294":{
      "scriptId":"u58"},
    "398698bff65e4d478204f2697daa7f8f":{
      "scriptId":"u59"},
    "bfdeb54d5e284622895090f09c2db2d8":{
      "scriptId":"u60"},
    "f80b9bdec39743bc8a42d45b3d71ab28":{
      "scriptId":"u61"},
    "f50fb99ec0be4a04842eec6836525daf":{
      "scriptId":"u62"},
    "cf4816abed884ef4a05c063f4db61755":{
      "scriptId":"u63"},
    "a41cfb135e4a41a8bc3bec4a1900a285":{
      "scriptId":"u64"},
    "4395a3ab368947c0b8caf57028b5e8f7":{
      "scriptId":"u65"},
    "40c95dd8b0864df79c98adf305cbf389":{
      "scriptId":"u66"},
    "4a5f86271a514d2bad6b207c7b0e4458":{
      "scriptId":"u67"},
    "beac4d631bc54b2c8bf1e6924bc752f1":{
      "scriptId":"u68"},
    "6362d91433864f2e9c93b10dba0a418a":{
      "scriptId":"u69"},
    "0e4a934be952454f8156596995ea5ea3":{
      "scriptId":"u70"},
    "c5d7ef931e0e4a658d531f975aa126be":{
      "scriptId":"u71"},
    "324bb6486a6c42a29b3a089d30621aea":{
      "scriptId":"u72"},
    "20de0fcd7a114d8dad3aa3207d2a867c":{
      "scriptId":"u73"},
    "e32e4416328d4763ac353b1ec1114841":{
      "scriptId":"u74"}}});